version: '2'

services:
    reverseproxy:
        container_name: reverseproxy
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /data/.well-known/:/usr/share/nginx/html/.well-known/
            - /etc/letsencrypt/live/davidproctor.io-0003/fullchain.pem:/etc/letsencrypt/live/davidproctor.io/fullchain.pem
            - /etc/letsencrypt/live/davidproctor.io-0003/privkey.pem:/etc/letsencrypt/live/davidproctor.io/privkey.pem

    davidproctor-io:
        container_name: davidproctor.io
        image: nginx:latest
        restart: always
        volumes:
            - /data/davidproctor.io:/usr/share/nginx/html
            - /data/.well-known/:/usr/share/nginx/html/.well-known/

    pizzarithmetic-com:
        container_name: pizzarithmetic.com
        image: nginx:latest
        restart: always
        volumes:
            - /data/pizzarithmetic.com:/usr/share/nginx/html
            - /data/.well-known/:/usr/share/nginx/html/.well-known/

    nextcloud-db:
        container_name: nextclouddb
        image: mariadb
        restart: always
        volumes:
            - /data/nextcloud-db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
            - MYSQL_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud

    angelaowre-com:
       container_name: angelaowre.com
       image: wordpress
       restart: always
       volumes:
           - /data/angelaowre.com:/usr/share/nginx/html
       environment:
           - WORDPRESS_DB_HOST=nextcloud-db
           - WORDPRESS_DB_USER=nextcloud
           - WORDPRESS_DB_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
           - WORDPRESS_TABLE_PREFIX=angelaowre_
           - WORDPRESS_DB_NAME=nextcloud
       mem_limit: 50m
       mem_reservation: 20m
       links:
           - nextcloud-db

    bartoszbos-com:
       container_name: bartoszbos.com
       image: wordpress
       restart: always
       volumes:
           - /data/bartoszbos.com:/usr/share/nginx/html
       environment:
           - WORDPRESS_DB_HOST=nextcloud-db
           - WORDPRESS_DB_USER=nextcloud
           - WORDPRESS_DB_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
           - WORDPRESS_TABLE_PREFIX=bartoszbos_
           - WORDPRESS_DB_NAME=nextcloud
       mem_limit: 50m
       mem_reservation: 20m
       links:
           - nextcloud-db

    ak747s-com:
        container_name: ak747s.com
        # build: ./Dockerfile-wordpress
        image: wordpress
        restart: always
        volumes:
            - /data/ak747s.com:/var/www/html
            - /data/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            - WORDPRESS_DB_HOST=nextcloud-db
            - WORDPRESS_DB_USER=nextcloud
            - WORDPRESS_DB_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
            - WORDPRESS_TABLE_PREFIX=ak747s_
            - WORDPRESS_DB_NAME=nextcloud
        links:
            - nextcloud-db

