version: '2'
 
services:
    reverseproxy:
        image: nginx:latest
        ports:
            - 80:8080
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /data/.well-known:/usr/share/nginx/html/.well-known
 
    davidproctor-io:
        depends_on:
            - reverseproxy
        image: nginx:latest
        restart: always
        volumes:
            - /data/davidproctor.io:/usr/share/nginx/html

    php:
        depends_on:
            - reverseproxy
        image: php:7-fpm
        ports:
            - 9000:9000
        restart: always
        volumes:
            - /data/pizzarithmetic.com:/usr/share/nginx/html
 
    pizzarithmetic-com:
        depends_on:
            - php
        image: nginx:latest
        restart: always
        volumes:
            - /data/pizzarithmetic.com:/usr/share/nginx/html
            - ./pizzarithmetic.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
