version: '2'

services:
    reverseproxy:
        container_name: reverseproxy
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /data/.well-known/:/usr/share/nginx/html/.well-known/
            - /etc/letsencrypt/live/davidproctor.io-0003/fullchain.pem:/etc/letsencrypt/live/davidproctor.io/fullchain.pem
            - /etc/letsencrypt/live/davidproctor.io-0003/privkey.pem:/etc/letsencrypt/live/davidproctor.io/privkey.pem

    davidproctor-io:
        container_name: davidproctor.io
        depends_on:
            - reverseproxy
        image: nginx:latest
        restart: always
        volumes:
            - /data/davidproctor.io:/usr/share/nginx/html
            - /data/.well-known/:/usr/share/nginx/html/.well-known/

    php:
        container_name: php
        depends_on:
            - reverseproxy
        image: php:7-fpm
        ports:
            - 9000:9000
        restart: always
        volumes:
            - /data/pizzarithmetic.com:/usr/share/nginx/html
 
    pizzarithmetic-com:
        container_name: pizzarithmetic.com
        depends_on:
            - php
        image: nginx:latest
        restart: always
        volumes:
            - /data/pizzarithmetic.com:/usr/share/nginx/html
            - ./pizzarithmetic.conf:/etc/nginx/conf.d/site.conf
            - /data/.well-known/:/usr/share/nginx/html/.well-known/
        links:
            - php

    nextcloud-db:
        container_name: nextclouddb
        depends_on:
            - reverseproxy
        image: mariadb
        restart: always
        volumes:
            - /data/nextcloud-db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
            - MYSQL_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud

    nextcloud:
       container_name: nextcloud
       depends_on:
           - nextcloud-db
       image: nextcloud
       links:
           - nextcloud-db
       volumes:
           - /data/nextcloud/main:/var/www/html
           - /data/nextcloud/apps:/var/www/html/custom_apps
           - /data/nextcloud/config:/var/www/html/config
           - /data/nextcloud/config:/var/www/html/data
           - /data/nextcloud/themes:/var/www/html/themes
       restart: always

    angelaowre-com:
       container_name: angelaowre.com
       image: wordpress
       restart: always
       volumes:
           - /data/angelaowre.com:/usr/share/nginx/html
       environment:
           - WORDPRESS_DB_HOST=nextcloud-db
           - WORDPRESS_DB_USER=nextcloud
           - WORDPRESS_DB_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
           - WORDPRESS_TABLE_PREFIX=angelaowre_
           - WORDPRESS_DB_NAME=nextcloud
       mem_limit: 50m
       mem_reservation: 20m
       links:
           - nextcloud-db

    bartoszbos-com:
       container_name: bartoszbos.com
       image: wordpress
       restart: always
       volumes:
           - /data/bartoszbos.com:/usr/share/nginx/html
       environment:
           - WORDPRESS_DB_HOST=nextcloud-db
           - WORDPRESS_DB_USER=nextcloud
           - WORDPRESS_DB_PASSWORD=hzEiF4C4Ej6q58hJ2bowFK6EwatxTbixtiGjf89j7TCpqDBYV9veGnTehMjspWEi
           - WORDPRESS_TABLE_PREFIX=bartoszbos_
           - WORDPRESS_DB_NAME=nextcloud
       mem_limit: 50m
       mem_reservation: 20m
       links:
           - nextcloud-db

